Website/Models/DatHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.DatHangCTs = new HashSet<DatHangCT>();
        }
    
        public int DatHangID { get; set; }
        public string Hoten { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public System.DateTime NgayDat { get; set; }
        public int TriGia { get; set; }
        public bool DaGiao { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangCT> DatHangCTs { get; set; }
    }
}

Website/Areas/Admin/Controllers/DatHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DatHangController : Controller
    {
        private VanShopEntities db = new VanShopEntities();

        // GET: Admin/DatHang
        public ActionResult Index()
        {
            return View(db.DatHangs.ToList());
        }

        // GET: Admin/DatHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHangs.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            return View(datHang);
        }

        // GET: Admin/DatHang/Create
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult Search(string tukhoa)
        {
            return PartialView(db.DatHangs.Where(m=>m.Hoten.Contains(tukhoa)).ToList());
        }
        // POST: Admin/DatHang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DatHangID,Hoten,DienThoai,DiaChi,Email,NgayDat,TriGia,DaGiao,NgayGiao,GhiChu")] DatHang datHang)
        {
            if (ModelState.IsValid)
            {
                db.DatHangs.Add(datHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(datHang);
        }

        // GET: Admin/DatHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHangs.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            return View(datHang);
        }

        // POST: Admin/DatHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DatHangID,Hoten,DienThoai,DiaChi,Email,NgayDat,TriGia,DaGiao,NgayGiao,GhiChu")] DatHang datHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(datHang);
        }

        // GET: Admin/DatHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHangs.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            return View(datHang);
        }

        // POST: Admin/DatHang/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int []dsxoa)
        {
            foreach(int id in dsxoa)
            {
                DatHang datHang = db.DatHangs.Find(id);
                IEnumerable<DatHangCT> dathangct = db.DatHangCTs.Where(m => m.DatHangID == id);
                foreach(var item in dathangct)
                {
                    db.DatHangCTs.Remove(item);
                }
                db.DatHangs.Remove(datHang);
            }          
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Website/Areas/Admin/Views/DatHang/Create.cshtml
@model Website.Models.DatHang

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>DatHang</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Hoten, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hoten, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hoten, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.TriGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TriGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TriGia, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DaGiao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.DaGiao)
                        @Html.ValidationMessageFor(model => model.DaGiao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.NgayGiao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Website/Areas/Admin/Views/DatHang/Index.cshtml
@model IEnumerable<Website.Models.DatHang>

@{
    ViewBag.Title = "Đơn đặt hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script>
        $(function () {
            $("#checkall").change(function () {
                if ($(this).prop("checked") == true) {
                    $("input[name=dsxoa]").prop("checked", true);
                }
                else {
                    $("input[name=dsxoa]").prop("checked", false);
                }
            });
        });
</script>  
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đơn đặt hàng</title>
</head>
<body>
    <div class="row">
        <div class="col-md-12">
            <h3 class="page-header">Danh sách các đơn đặt hàng</h3>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                   Đơn đặt hàng
                </div>
                <div class="panel-body">
                    <div id="dataTables-example_wrapper" class="dataTable_wrapper form-inline dt-bootstrap no-footer">
                        <div class="col-md-12">
                            <div id="dataTables-example_filter" class="dataTable_filter">
                                @using (Ajax.BeginForm("Search", "DatHang", new { areas = "Admin" }, new AjaxOptions() { AllowCache = true, HttpMethod = "Get", OnFailure = "alert('Lỗi ajax')", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divTable_DonHang" }, new { id = "frmSearch_DonHang" }))
                                 {
                                    <div class="col-md-1">
                                        <label>Tìm kiếm: </label>
                                    </div>
                                    <div class="col-md-11">
                                        <input onkeyup="document.getElementById('btnSubmitTim').click()" type="text" id="tukhoa" name="tukhoa" class="form-control input-sm" placeholder="Nhập tên sản phẩm cần tìm" aria-controls="dataTable" style="border-radius:10px">
                                        <button type="submit" id="btnSubmitTim" class="btn btn-sm hidden">Tìm</button>
                                    </div>

                                }

                            </div>
                        </div>
                        <div class="col-md-12" id="divTable_DonHang" style="margin-top:20px">
                            <form action="@Url.Action("Delete","DatHang")" method="post">
                                <div class="col-md-12">
                                    <table class="table table-striped table-bordered table-hover">
                                        <tr>
                                            <th>
                                                <input type="checkbox" id="checkall" />
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Họ tên")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Điện thoại")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Địa chỉ")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayNameFor(model => model.Email)
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Ngày đặt")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Trị giá đơn hàng")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Đã giao")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Ngày giao hàng")
                                            </th>
                                            <th style="vertical-align:middle;text-align:center">
                                                @Html.DisplayName("Ghi chú")
                                            </th>
                                            <th></th>
                                        </tr>

                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td class="text-center">
                                                    <input type="checkbox" name="dsxoa" value="@item.DatHangID" />
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Hoten)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DienThoai)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DiaChi)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NgayDat)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.TriGia)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DaGiao)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NgayGiao)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.GhiChu)
                                                </td>
                                                <td>
                                                    <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#donhang@(item.DatHangID)">Xem chi tiết</button>
                                                    <div id="donhang@(item.DatHangID)" class="modal fade" role="dialog">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                    <h4 class="modal-title">Chi tiết hộp thư của <span class="text-danger">@item.Hoten</span> </h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <table class="table table-striped table-bordered">
                                                                        <thead>
                                                                            <tr>
                                                                                <th></th>
                                                                                <th>Tên sản phẩm</th>
                                                                                <th>Số lượng</th>
                                                                                <th>Đơn giá</th>
                                                                                <th>Thành tiền</th>
                                                                            </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                            @foreach (var item_SanPham in item.DatHangCTs)
                                                                            {
                                                                                <tr>
                                                                                    <td>
                                                                                        <img src="~/Content/images/Photos/@item_SanPham.SanPham.Hinh" alt="@item_SanPham.SanPham.BiDanh" width="90" height="110" />
                                                                                    </td>
                                                                                    <td>@item_SanPham.SanPham.TenSanPham</td>
                                                                                    <td>@item_SanPham.SoLuong</td>
                                                                                    <td>@item_SanPham.DonGia</td>
                                                                                    <td>@item_SanPham.ThanhTien</td>
                                                                                </tr>
                                                                            }

                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    @Html.ActionLink("Sửa", "Edit", new { id = item.DatHangID }, new { @class = "btn btn-xs btn-default" })
                                                                    <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    @*@Html.ActionLink("Xem chi tiết", "Details", new { id = item.HopThuID }, new { @class = "btn btn-primary btn-xs" })*@
                                                    @Html.ActionLink("Sửa", "Edit", new { id = item.DatHangID }, new { @class = "btn btn-default btn-xs" })
                                                </td>
                                            </tr>
                                        }
                                        <tr>
                                            <td colspan="11" style="text-align:right">
                                                <input type="submit" class="btn btn-danger btn-sm " value="Xóa" onclick="return confirm('Bạn có chắc chắn muốn xóa không ?')" />
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                               
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Website/Areas/Admin/Views/DatHang/Search.cshtml
@using Website.Models;
@model IEnumerable<DatHang>
    <form action="@Url.Action("Delete","DatHang")" method="post">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover">
                <tr>
                    <th>
                        <input type="checkbox" id="checkall" />
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Họ tên")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Điện thoại")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Địa chỉ")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Ngày đặt")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Trị giá đơn hàng")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Đã giao")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Ngày giao hàng")
                    </th>
                    <th style="vertical-align:middle;text-align:center">
                        @Html.DisplayName("Ghi chú")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">
                            <input type="checkbox" name="dsxoa" value="@item.DatHangID" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Hoten)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DienThoai)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayDat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TriGia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DaGiao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayGiao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GhiChu)
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#donhang@(item.DatHangID)">Xem chi tiết</button>
                            <div id="donhang@(item.DatHangID)" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Chi tiết hộp thư của <span class="text-danger">@item.Hoten</span> </h4>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th></th>
                                                        <th>Tên sản phẩm</th>
                                                        <th>Số lượng</th>
                                                        <th>Đơn giá</th>
                                                        <th>Thành tiền</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var item_SanPham in item.DatHangCTs)
                                                    {
                                                        <tr>
                                                            <td>
                                                                <img src="~/Content/images/Photos/@item_SanPham.SanPham.Hinh" alt="@item_SanPham.SanPham.BiDanh" width="90" height="110" />
                                                            </td>
                                                            <td>@item_SanPham.SanPham.TenSanPham</td>
                                                            <td>@item_SanPham.SoLuong</td>
                                                            <td>@item_SanPham.DonGia</td>
                                                            <td>@item_SanPham.ThanhTien</td>
                                                        </tr>
                                                    }

                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.DatHangID }, new { @class = "btn btn-xs btn-default" })
                                            <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @*@Html.ActionLink("Xem chi tiết", "Details", new { id = item.HopThuID }, new { @class = "btn btn-primary btn-xs" })*@
                            @Html.ActionLink("Sửa", "Edit", new { id = item.DatHangID }, new { @class = "btn btn-default btn-xs" })
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="11" style="text-align:right">
                        <input type="submit" class="btn btn-danger btn-sm " value="Xóa" onclick="return confirm('Bạn có chắc chắn muốn xóa không ?')" />
                    </td>
                </tr>
            </table>
        </div>

    </form>
<script>
        $(function () {
            $("#checkall").change(function () {
                if ($(this).prop("checked") == true) {
                    $("input[name=dsxoa]").prop("checked", true);
                }
                else {
                    $("input[name=dsxoa]").prop("checked", false);
                }
            });
        });
</script>