Website/Models/HopThu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopThu
    {
        public int HopThuID { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public bool DaDoc { get; set; }
        public string SDT { get; set; }
        public string TieuDe { get; set; }
    }
}

Website/Areas/Admin/Controllers/HopThuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HopThuController : Controller
    {
        private VanShopEntities db = new VanShopEntities();

        // GET: Admin/HopThu
        public ActionResult Index()
        {
            return View(db.HopThus.ToList());
        }

        // GET: Admin/HopThu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopThu hopThu = db.HopThus.Find(id);
            if (hopThu == null)
            {
                return HttpNotFound();
            }
            return View(hopThu);
        }

        // GET: Admin/HopThu/Create
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult Search(string tukhoa)
        {
            return PartialView(db.HopThus.Where(m => m.Hoten.Contains(tukhoa)).ToList());
        }
        // POST: Admin/HopThu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HopThuID,Hoten,Email,NoiDung,NgayCapNhat,DaDoc,SDT,TieuDe")] HopThu hopThu)
        {
            if (ModelState.IsValid)
            {
                db.HopThus.Add(hopThu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hopThu);
        }

        // GET: Admin/HopThu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopThu hopThu = db.HopThus.Find(id);
            if (hopThu == null)
            {
                return HttpNotFound();
            }
            return View(hopThu);
        }

        // POST: Admin/HopThu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HopThuID,Hoten,Email,NoiDung,NgayCapNhat,DaDoc,SDT,TieuDe")] HopThu hopThu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hopThu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hopThu);
        }

        // GET: Admin/HopThu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopThu hopThu = db.HopThus.Find(id);
            if (hopThu == null)
            {
                return HttpNotFound();
            }
            return View(hopThu);
        }

        // POST: Admin/HopThu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HopThu hopThu = db.HopThus.Find(id);
            db.HopThus.Remove(hopThu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Website/Areas/Admin/Views/HopThu/Create.cshtml
@model Website.Models.HopThu

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HopThu</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Hoten, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hoten, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hoten, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DaDoc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.DaDoc)
                        @Html.ValidationMessageFor(model => model.DaDoc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Website/Areas/Admin/Views/HopThu/Delete.cshtml
@model Website.Models.HopThu

@{
    ViewBag.Title = "Hộp thư";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Xóa</title>
</head>
<body>
    <h4 style="padding-top:20px">Bạn chắc chắn có muốn xóa thư của <span style="text-decoration:underline" class="text-danger">@Model.Hoten</span> không ?</h4>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model=>model.Hoten)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hoten)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.NgayCapNhat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayCapNhat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DaDoc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DaDoc)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.TieuDe)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TieuDe)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.NoiDung)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NoiDung)
            </dd>
      
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                @Html.ActionLink("Về danh sách", "Index", null, new { @class = "btn btn-sm btn-success" })
                <input type="submit" value="Xóa" class="btn btn-default" /> 
                
            </div>
        }
    </div>
</body>
</html>

Website/Areas/Admin/Views/HopThu/Details.cshtml
@model Website.Models.HopThu

@{
    ViewBag.Title = "Hộp thư";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Xem chi tiết</title>
</head>
<body>
    <div>
        <h4 style="padding-top:20px">Chi tiết hộp thư của <span style="text-decoration:underline" class="text-danger">@Model.Hoten</span></h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
               @Html.DisplayNameFor(model => model.Hoten)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Hoten)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.NgayCapNhat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayCapNhat)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.DaDoc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DaDoc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TieuDe)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TieuDe)
            </dd>

            <dt>
               @Html.DisplayNameFor(model => model.NoiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NoiDung)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Sửa", "Edit", new { id = Model.HopThuID }, new { @class = "btn btn-sm btn-default" })
        @Html.ActionLink("Về danh sách", "Index", null, new { @class = "btn btn-sm btn-success" })
    </p>
</body>
</html>

Website/Areas/Admin/Views/HopThu/Edit.cshtml
@model Website.Models.HopThu

@{
    ViewBag.Title = "Hộp thư";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sửa</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4 style="padding-top:20px">Sửa thông tin hộp thư của <span style="text-decoration:underline" class="text-danger">@Model.Hoten</span> </h4>
            <hr />
            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
            @Html.HiddenFor(model => model.HopThuID)
    
            <div class="form-group">
                @Html.LabelFor(model=>model.Hoten, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Hoten, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hoten, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
                </div>
            </div>

    
            <div class="form-group">
                @Html.LabelFor(model => model.DaDoc, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.DaDoc)
                        @Html.ValidationMessageFor(model => model.DaDoc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            
    
            <div class="form-group">
                @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-4 col-md-6">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Về danh sách", "Index", null, new { @class = "btn btn-sm btn-success" })
    </div>
</body>
</html>

Website/Areas/Admin/Views/HopThu/Index.cshtml
@model IEnumerable<Website.Models.HopThu>

@{
    ViewBag.Title = "Hộp thư";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hộp thư</title>
</head>
<body>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Danh sách hộp thư</h3>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                   Hộp thư
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div id="dataTables-example_wrapper" class="dataTable_wrapper form-inline dt-bootstrap no-footer">
                        <div class="col-md-12">
                            <div id="dataTables-example_filter" class="dataTable_filter">
                                @using (Ajax.BeginForm("Search", "HopThu", new { areas = "Admin" }, new AjaxOptions() { AllowCache = true, HttpMethod = "Get", OnFailure = "alert('Lỗi ajax')", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divTable_HopThu" }, new { id = "frmSearch_DonHang" }))
                                 {
                                    <div class="col-md-1">
                                        <label>Tìm kiếm: </label>
                                    </div>
                                    <div class="col-md-11">
                                        <input onkeyup="document.getElementById('btnSubmitTim').click()" type="text" id="tukhoa" name="tukhoa" class="form-control input-sm" placeholder="Nhập tên sản phẩm cần tìm ..." aria-controls="dataTable" style="border-radius:10px">
                                        <button type="submit" id="btnSubmitTim" class="btn btn-sm hidden">Tìm</button>
                                    </div>

                                }

                            </div>
                        </div>

                        <div id="divTable_HopThu" class="col-md-12" style="margin-top:20px">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayNameFor(model => model.Hoten)
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayNameFor(model => model.Email)
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayName("Điện thoại")
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayName("Ngày cập nhập")
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayName("Đã đọc")
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayName("Tiêu đề")
                                        </th>
                                        <th style="vertical-align:middle;text-align:center">
                                            @Html.DisplayName("Nội dung")
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Hoten)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.SDT)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NgayCapNhat)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DaDoc)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TieuDe)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NoiDung)
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#hopthu@(item.HopThuID)">Xem chi tiết</button>
                                                <div id="hopthu@(item.HopThuID)" class="modal fade" role="dialog">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <h4 class="modal-title">Chi tiết hộp thư của <span class="text-danger">@item.Hoten</span> </h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <table class="table table-striped table-bordered">
                                                                    <tr>
                                                                        <th>Họ tên</th>
                                                                        <th>Email</th>
                                                                        <th>Nội dung</th>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>@item.Hoten</td>
                                                                        <td>@item.Email</td>
                                                                        <td>@item.NoiDung</td>
                                                                    </tr>
                                                                </table>
                                                            </div>
                                                            <div class="modal-footer">
                                                                @Html.ActionLink("Sửa", "Edit", new { id = item.HopThuID }, new { @class = "btn btn-xs btn-default" })
                                                                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                @*@Html.ActionLink("Xem chi tiết", "Details", new { id = item.HopThuID }, new { @class = "btn btn-primary btn-xs" })*@
                                                @Html.ActionLink("Sửa", "Edit", new { id = item.HopThuID }, new { @class = "btn btn-default btn-xs" })
                                                @Html.ActionLink("Xóa", "Delete", new { id = item.HopThuID }, new { @class = "btn btn-default btn-xs" })
                                            </td>
                                        </tr>
                                    }
                                </tbody>                            
                            </table>
                        </div>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</body>
</html>

Website/Areas/Admin/Views/HopThu/Search.cshtml
@using Website.Models;
@model IEnumerable<HopThu>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Họ tên")
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Điện thoại")
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Ngày cập nhập")
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Đã đọc")
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Tiêu đề")
        </th>
        <th style="vertical-align:middle;text-align:center">
            @Html.DisplayName("Nội dung")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hoten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaDoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TieuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDung)
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#hopthu@(item.HopThuID)">Xem chi tiết</button>
                <div id="hopthu@(item.HopThuID)" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Chi tiết hộp thư của <span class="text-danger">@item.Hoten</span> </h4>
                            </div>
                            <div class="modal-body">
                                <table class="table table-striped table-bordered">
                                    <tr>
                                        <th>Họ tên</th>
                                        <th>Email</th>
                                        <th>Nội dung</th>
                                    </tr>
                                    <tr>
                                        <td>@item.Hoten</td>
                                        <td>@item.Email</td>
                                        <td>@item.NoiDung</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="modal-footer">
                                @Html.ActionLink("Sửa", "Edit", new { id = item.HopThuID }, new { @class = "btn btn-xs btn-default" })
                                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                @*@Html.ActionLink("Xem chi tiết", "Details", new { id = item.HopThuID }, new { @class = "btn btn-primary btn-xs" })*@
                @Html.ActionLink("Sửa", "Edit", new { id = item.HopThuID }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.HopThuID }, new { @class = "btn btn-default btn-xs" })
            </td>
        </tr>
    }

</table>